spring:
#  jpa:
#    show-sql: true # SQL 쿼리 출력
#    properties:
#      hibernate:
#        format_sql: true # 쿼리를 보기좋게 포맷팅
#    defer-datasource-initialization: true # SQL 파일을 지연 초기화(테스트용)
#  datasource:
#    url: jdbc:h2:mem:testdb # h2 인메모리 설정
#  h2:
#    console:
#      enabled: true # h2 웹 콘솔 활성화
  datasource:
    url: jdbc:mysql://localhost:3306/kafka_capstone_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${ec2-ip}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  profiles:
    include:
      KEY

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace # hibernate 바인딩 값(물음표 값) 로그 출력
    org.springframework.security: DEBUG




